/* Maple V3.4: explicit zone risks and local-swing evidence, not buy signals. */
let rows=[], activeFilter="all", lastGeneratedAt=null, lastLoadAt=0, loading=false;
const list=document.getElementById("list"), tpl=document.getElementById("rowTemplate"),
 search=document.getElementById("search"), count=document.getElementById("count"),
 empty=document.getElementById("empty"), updated=document.getElementById("updated"),
 sectionHeading=document.getElementById("sectionHeading"), refreshBtn=document.getElementById("refreshBtn");
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const pct=v=>Number.isFinite(v)?(v>=0?"+":"")+v.toFixed(2)+"%":"—";
const money=v=>Number.isFinite(v)?"$"+v.toFixed(v>=100?2:3):"—";
const zoneText=z=>z&&Number.isFinite(z.low)&&Number.isFinite(z.high)?money(z.low)+"–"+money(z.high):"—";
function dateText(iso){
  if(!/^\d{4}-\d{2}-\d{2}$/.test(iso||""))return "unknown";
  const d=new Date(iso+"T12:00:00");
  return Number.isNaN(d.getTime())?"unknown":d.toLocaleDateString([], {year:"numeric",month:"short",day:"numeric"});
}
function retestText(z){
  if(!z)return "No qualifying candidate";
  if(!Number.isInteger(z.touch_bars))return "Legacy counts — awaiting V3.4 scan";
  const n=z.retests, days=z.touch_bars;
  return (n===0&&!z.wick_breached?"Untested • ":"")+n+" separate "+(n===1?"visit":"visits")+
    " • "+days+" daily "+(days===1?"candle":"candles")+" touched";
}
function zoneMeta(z){
  if(!z)return "No qualifying candidate";
  return "Formed "+dateText(z.formed_at)+" • "+retestText(z)+
    (z.wick_breached?" • BOUNDARY BREACHED":"");
}
const isCurrent=r=>r.rules_version==="3.4";
const cleanDemand=r=>isCurrent(r)&&r.demand_zone&&r.demand_zone.valid&&!r.demand_zone.wick_breached&&!r.overlap_conflict;
function bounceLabel(r){
  if(!isCurrent(r))return "Legacy signal — needs rescan";
  if(r.demand_bounce==="swing_break")return "Completed local swing break";
  if(r.demand_bounce==="early")return r.bar_is_provisional?"Early bounce • provisional":"Early bounce • unconfirmed";
  return "No clean bounce signal";
}
function badge(text,type=""){return '<span class="badge '+type+'">'+esc(text)+'</span>';}
function swingView(r){
  if(!isCurrent(r))return {cls:"caution",label:"Waiting for V3.4 recheck",detail:"These results were generated by an older ruleset. Do not treat old confirmation labels as verified."};
  if(r.overlap_conflict)return {cls:"caution",label:"Conflicting zones — caution",detail:"Demand and supply overlap. Neither zone is being hidden to make this look like a clean setup."};
  if(r.demand_zone?.wick_breached)return {cls:"caution",label:"Demand boundary breached",detail:"Price traded below demand. This candidate survives only under the completed-close rule, is downgraded, and is excluded from clean bounce signals."};
  if(!r.demand_zone)return {cls:"avoid",label:"No qualifying demand candidate",detail:"The local-pivot and zone checks did not identify usable demand. A missing zone is not an entry signal."};
  if(r.supply_zone?.wick_breached)return {cls:"caution",label:"Supply boundary breached",detail:"The displayed opposing zone has been traded through. Its boundary history needs manual review."};
  const sd=r.supply_distance_pct,dd=r.demand_distance_pct;
  if(sd==null)return {cls:"watch",label:"Upside room is unknown",detail:"No qualifying opposing supply candidate was found. Missing supply does not mean unlimited room to rise."};
  if(sd<=2)return {cls:"caution",label:"Watch — supply is close",detail:"Nearby supply limits room. The score is a rule-based ranking, not a probability of success."};
  if(r.demand_bounce==="swing_break"&&cleanDemand(r))return {cls:"watch",label:"Local swing break recorded",detail:"A completed prior-session candle broke a known local lower high after the demand visit. This is evidence to review, not a guaranteed reversal or buy recommendation."};
  if(dd!=null&&dd<=3)return {cls:"watch",label:"Watch — reaction not confirmed",detail:"Price is near demand, but there is no qualifying completed local lower-high break. Today's daily candle remains provisional."};
  return {cls:"avoid",label:"Wait for a clearer setup",detail:"Review zone location, boundary warnings and price-candle date before treating this ranking as actionable."};
}
function setText(root,selector,value){const el=root.querySelector(selector);if(el)el.textContent=value;}
function render(){
  const q=search.value.trim().toLowerCase();
  const filtered=rows.filter(r=>{
    const text=(r.symbol+" "+r.name).toLowerCase();
    const near=r.demand_distance_pct!=null&&r.demand_distance_pct<=3;
    const fresh=cleanDemand(r)&&r.demand_zone.touch_bars===0;
    const bounce=cleanDemand(r)&&["early","swing_break"].includes(r.demand_bounce);
    return text.includes(q)&&(activeFilter==="all"||r.type===activeFilter||
      (activeFilter==="bounce"&&bounce)||(activeFilter==="demand"&&near)||(activeFilter==="fresh"&&fresh));
  });
  filtered.sort(activeFilter==="bounce"?((a,b)=>(b.bounce_score||0)-(a.bounce_score||0)||b.score-a.score):((a,b)=>b.score-a.score));
  sectionHeading.textContent=activeFilter==="bounce"?"Demand bounces — evidence, not guarantees":"Top setups";
  const fragment=document.createDocumentFragment();
  filtered.forEach((r,i)=>{
    const n=tpl.content.cloneNode(true);
    setText(n,".rank",i+1);setText(n,".symbol",r.symbol);setText(n,".name",r.name);
    const score=n.querySelector(".score");score.textContent=Math.round(r.score);
    score.classList.add(r.score>=80?"good":r.score>=60?"mid":"low");
    score.title="Rule-based score; not a win probability";
    setText(n,".price",money(r.price));setText(n,".rsi",Number.isFinite(r.rsi)?r.rsi.toFixed(0):"—");
    setText(n,".demand",zoneText(r.demand_zone));setText(n,".supply",zoneText(r.supply_zone));
    setText(n,".demand-meta",zoneMeta(r.demand_zone));setText(n,".supply-meta",zoneMeta(r.supply_zone));
    const meta=document.createElement("p");meta.className="candle-meta";
    meta.textContent=isCurrent(r)?"Price candle: "+dateText(r.last_candle_date)+
      (r.bar_is_provisional?" • provisional":"")+". Completed-candle checks through "+dateText(r.validated_through)+".":
      "Older scan — awaiting V3.4 validation.";
    n.querySelector(".metrics").after(meta);
    const warnings=Array.isArray(r.warnings)?r.warnings:[];
    if(warnings.length){
      const panel=document.createElement("div");panel.className="zone-warnings";
      panel.innerHTML="<strong>Zone cautions</strong><ul>"+warnings.map(x=>"<li>"+esc(x)+"</li>").join("")+"</ul>";
      meta.after(panel);
    }
    if(i===0){
      const sv=swingView(r),el=n.querySelector(".swing-view");
      el.classList.remove("hidden");el.classList.add(sv.cls);
      el.innerHTML='<span class="swing-kicker">RULE-BASED SETUP CHECK</span><b>'+esc(sv.label)+'</b><small>'+esc(sv.detail)+'</small>';
    }
    const b=[];
    if(["early","swing_break"].includes(r.demand_bounce)&&cleanDemand(r))b.push(badge(bounceLabel(r),r.demand_bounce==="swing_break"?"positive":""));
    if(r.demand_zone?.wick_breached)b.push(badge("Demand boundary breached","warning"));
    if(r.supply_zone?.wick_breached)b.push(badge("Supply boundary breached","warning"));
    if(r.overlap_conflict)b.push(badge("Overlapping zones","warning"));
    if(r.demand_distance_pct!=null&&r.demand_distance_pct<=0.35)b.push(badge("At / near demand"));
    else if(r.demand_distance_pct!=null&&r.demand_distance_pct<=3)b.push(badge("Near demand"));
    if(cleanDemand(r)&&r.demand_zone.touch_bars===0)b.push(badge("Untested demand","positive"));
    if(r.trend==="bullish"&&r.weekly_trend==="bullish")b.push(badge("D+W bull trend","positive"));
    if(r.supply_distance_pct!=null&&r.supply_distance_pct<=3)b.push(badge("Near supply","warning"));
    b.push(badge((r.type||"asset").toUpperCase()));
    n.querySelector(".badges").innerHTML=b.join("");
    const why=n.querySelector(".why");
    const details=["Demand: "+zoneText(r.demand_zone)+" • "+zoneMeta(r.demand_zone),
      "Supply: "+zoneText(r.supply_zone)+" • "+zoneMeta(r.supply_zone),
      "Distance to demand: "+pct(r.demand_distance_pct),"Distance to supply: "+pct(r.supply_distance_pct),
      "Reaction: "+bounceLabel(r),r.bounce_detail||"",
      "Local lower high: "+money(r.bounce_swing_high)+" • "+dateText(r.bounce_swing_high_at),
      "Completed break date: "+dateText(r.bounce_break_at)];
    for(const [label,z] of [["Demand",r.demand_zone],["Supply",r.supply_zone]]){
      if(!z)continue;
      details.push(label+" first eligible: "+dateText(z.confirmed_at));
      details.push(label+" longest continuous visit: "+(z.max_consecutive_touch_bars??"unknown")+" daily candles");
      if(z.wick_breached)details.push(label+" first breach: "+dateText(z.first_breach_at)+" • extreme "+money(z.breach_extreme));
    }
    why.innerHTML="<ul>"+(r.reasons||[]).map(x=>"<li>"+esc(x)+"</li>").join("")+"</ul>"+
      '<div class="zone-stats">'+details.filter(Boolean).map(x=>"<span>"+esc(x)+"</span>").join("")+"</div>";
    const btn=n.querySelector(".why-btn");btn.addEventListener("click",()=>{
      why.classList.toggle("hidden");btn.textContent=why.classList.contains("hidden")?"Why this score ▾":"Hide details ▴";
    });
    fragment.appendChild(n);
  });
  list.replaceChildren(fragment);count.textContent=filtered.length+" shown";
  empty.classList.toggle("hidden",filtered.length!==0);
}
function formatStamp(iso){
  const d=new Date(iso);return Number.isNaN(d.getTime())?"unknown":d.toLocaleString([], {month:"short",day:"numeric",hour:"numeric",minute:"2-digit"});
}
async function fetchScan(){
  const bust=Date.now();
  const urls=["https://raw.githubusercontent.com/bsteeves1/maple-zones/main/data/scan.json?ts="+bust,"data/scan.json?ts="+bust];
  for(const url of urls){
    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);
    try{
      const response=await fetch(url,{cache:"no-store",signal:controller.signal});
      if(!response.ok)throw new Error("HTTP "+response.status);
      const data=await response.json();
      if(!Array.isArray(data.results)||!Number.isFinite(Date.parse(data.generated_at)))throw new Error("Invalid scan schema");
      if(lastGeneratedAt&&Date.parse(data.generated_at)<Date.parse(lastGeneratedAt))continue;
      if(!data.results.every(r=>typeof r.symbol==="string"&&Number.isFinite(r.price)&&Number.isFinite(r.score)))throw new Error("Invalid scan rows");
      return data;
    }catch(e){console.warn("Scan source unavailable",e.message);}finally{clearTimeout(timer);}
  }
  throw new Error("No usable scan source");
}
async function load({quiet=false}={}){
  if(loading)return;loading=true;lastLoadAt=Date.now();refreshBtn.disabled=true;
  if(!quiet)updated.textContent=lastGeneratedAt?"Checking for a newer scan…":"Loading scan…";
  try{
    const data=await fetchScan(),changed=data.generated_at!==lastGeneratedAt;
    rows=data.results;lastGeneratedAt=data.generated_at;
    const age=Math.max(0,Math.floor((Date.now()-Date.parse(lastGeneratedAt))/60000));
    updated.textContent="Scan completed "+formatStamp(lastGeneratedAt)+" • "+age+" min old • checked "+new Date().toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})+
      (rows.some(r=>!isCurrent(r))?" • awaiting V3.4 rescan":"")+(age>15?" • scan is aging":"");
    if(changed||!list.children.length)render();
  }catch(e){
    updated.textContent=lastGeneratedAt?"Refresh failed — retaining scan from "+formatStamp(lastGeneratedAt):"Scan could not load — tap ↻ to retry";
  }finally{loading=false;refreshBtn.disabled=false;}
}
search.addEventListener("input",render);
document.getElementById("filters").addEventListener("click",e=>{
  if(!e.target.matches(".chip"))return;
  document.querySelectorAll(".chip").forEach(x=>x.classList.remove("active"));
  e.target.classList.add("active");activeFilter=e.target.dataset.filter;render();
});
refreshBtn.addEventListener("click",()=>load());
if("serviceWorker" in navigator){
  const controlled=Boolean(navigator.serviceWorker.controller);let reloading=false;
  navigator.serviceWorker.addEventListener("controllerchange",()=>{if(controlled&&!reloading){reloading=true;location.reload();}});
  navigator.serviceWorker.register("sw.js",{updateViaCache:"none"}).then(reg=>reg.update()).catch(()=>{});
}
const AUTO_REFRESH_MS=15000;
setInterval(()=>{if(document.visibilityState==="visible")load({quiet:true});},AUTO_REFRESH_MS);
document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"&&Date.now()-lastLoadAt>=AUTO_REFRESH_MS)load({quiet:true});});
load();
